/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.headphonebuttons;

import org.appcelerator.kroll.KrollDict;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.KeyEvent;

public class MediaButtonReceiver extends BroadcastReceiver {
	public static final String LCAT = "HeadPhoneButtons  📢📢";

	public MediaButtonReceiver() {
		super();
	}

	@Override
	public void onReceive(Context context, Intent intent) {
		String intentAction = intent.getAction();
		Log.d(LCAT,
				">>>>>>>>>>>>>>>>>>>>>>>>>>>> onReceive " + intent.toString());
		if (!Intent.ACTION_MEDIA_BUTTON.equals(intentAction)) {
			return;
		}
		KeyEvent event = (KeyEvent) intent
				.getParcelableExtra(Intent.EXTRA_KEY_EVENT);
		if (event == null) {
			return;
		}
		int action = event.getAction();
		if (action == KeyEvent.ACTION_DOWN) {
			KrollDict dict = new KrollDict();
			dict.put("keycode", action);
			// callback.callAsync(getKrollObject(), dict);
		}
		// abortBroadcast();
	}
}
