/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.headphonebuttons;

import org.appcelerator.kroll.KrollDict;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.GestureDetector;
import android.view.KeyEvent;
import android.view.MotionEvent;

public class MediaButtonReceiver extends BroadcastReceiver {
	public static final String LCAT = "HeadPhoneButtons  📢📢";

	@Override
	public void onReceive(Context context, Intent intent) {
		KeyEvent event = (KeyEvent) intent
				.getParcelableExtra(Intent.EXTRA_KEY_EVENT);
		Log.d(LCAT, event.toString());
		KrollDict dict = new KrollDict();
		dict.put("action", event.getAction());
		dict.put("keyCode", event.getKeyCode());

		Log.d(LCAT, dict.toString());
		HeadphonebuttonsModule.sendBack(dict);

		// abortBroadcast();
	}

	private class GestureListener extends
			GestureDetector.SimpleOnGestureListener {

		@Override
		public boolean onDown(MotionEvent e) {
			return true;
		}

		// event when double tap occurs
		@Override
		public boolean onDoubleTap(MotionEvent e) {
			float x = e.getX();
			float y = e.getY();

			return true;
		}
	}
}
